#!/bin/sh

if [ $# -ne 1 ]
then
  echo "mk-html-footer: usage: file" 1>&2
  exit 111
fi

title=`head -n 1 "$1"` || exit 1
cat <<EOF
<div class="core_footer">
  <hr />
  <a href="/">coreland</a> / <a href="/doc">doc</a> - ${title}
</div>
EOF
